import React from 'react'
import Head from 'next/head'
import Header from '@/components/Header'
import HeroSection from '@/components/HeroSection'
import { motion, useScroll, useSpring } from 'framer-motion'
import dynamic from 'next/dynamic'

const TechStackScroll = dynamic(() => import('@/components/TechStack-scroll'), {
  ssr: false, // skip server-side bundle
  loading: () => null,
})

const Projects = dynamic(() => import('@/components/Projects'), { ssr: false })
const Home: React.FC = () => {
  const { scrollYProgress } = useScroll()
  const scaleX = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001,
  })

  // Define the motion div with proper typing
  const MotionDiv = motion.div as any

  return (
    <>
      <Head>
        <title>Kasoma Ibrahim</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <Header />
      <MotionDiv
        className='fixed top-0 left-0 right-0 h-1 bg-red-400 z-50'
        style={{ scaleX, originX: 0 }}
      />
      <div className='max-w-[1400px] m-auto'>
        <HeroSection />
      </div>
      <div className='max-w-[1400px] m-auto' id='tech-stack'>
        <TechStackScroll />
      </div>
      <div>
        <Projects />
      </div>
    </>
  )
}

export default Home
