import Head from "next/head";
import Header from "../components/Header";
import HeroSection from "../components/HeroSection";
import Projects from "../components/Projects";
import { motion, useScroll, useSpring } from "framer-motion";
export default function Home() {
  const { scrollYProgress } = useScroll();
  const scaleX = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001,
  });
  return (
    <>
      <Head>
        <title>Kasoma Ibrahim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <motion.div
        className="fixed top-0 left-0 right-0 h-1 bg-red-400 z-50"
        style={{ scaleX, originX: 0 }}
      />
      <div className="max-w-[1400px] m-auto">
        <HeroSection />
      </div>
      <div>
        <Projects />
      </div>
    </>
  );
}
